// <auto-generated />
namespace Reciklaza.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Triedaddingfilter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Triedaddingfilter));
        
        string IMigrationMetadata.Id
        {
            get { return "201810041813456_Tried adding filter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
